version: "3.5"
services:
  php:
    depends_on:
        - mysql
    build:
      context: './docker/php/'
    volumes:
      - ./:/var/www/app/
      - ${SSH_DIRECTORY}:/root/ssh
    command: sh -c "
      cd /var/www/app && cp -R /root/ssh /root/.ssh && chown -R root:root /root/.ssh && chmod -R 400 /root/.ssh && ssh-keyscan bitbucket.org >> /root/.ssh/known_hosts
        ssh-keygen -R bitbucket.org &&
        composer config --no-plugins allow-plugins.php-http/discovery true &&
        composer install --no-interaction &&
        php artisan key:generate &&
        php artisan config:clear &&
        php artisan cache:clear &&
        chmod 777 -R storage bootstrap &&
        ./wait-for-mysql.sh &&
        php artisan migrate --force &&
        php-fpm"
  nginx:
    container_name: nginx
    image: nginx:alpine
    depends_on:
      - php
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/app/
      - ./docker/nginx/sites/:/etc/nginx/conf.d
  mysql:
    image: mariadb:10.9.4
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=laravel
      - MYSQL_DATABASE=laravel
    volumes:
      - ./:/var/www/app/
      - ./docker/mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_HOST=mysql
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER_NAME=root
  ngrok:
      image: wernight/ngrok:latest
      ports:
          - 4040:4040
      links:
          - nginx
      environment:
          - NGROK_LOOK_DOMAIN=nginx
          - NGROK_PORT=80
          - NGROK_AUTH=1vG0dmVF4Qux6u2egVNDEdBXI2w_6TogzyXqc3EYX1fxFmDxk
      volumes:
          - ../${NAME}:/var/app/www
  redis:
    build:
      context: ./docker/redis
networks:
  default:
    driver: bridge
